engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 100
ratings:
  paths:
  - "*.js"
  - ara/*.js
  - eng/*.js
  - jpn/*.js

exclude_paths:
- dist/*
- design/*
- node_modules/*
