files:

  # define files included in the analysis (defaults to ["{app,lib}/**/*.rb"])
  included:
    - *.js
    - ara/*.js
    - eng/*.js
    - jpn/*.js
    
  # define files excluded from the analysis (defaults to [])
  excluded:
    - test/*
    - node_modules/*
    - dist/*
