language: node_js
node_js:
  - '6'
  - '0.10'

jobs:
  include:
    - stage: npm release
      node_js: "6"
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: kariminfo0@gmail.com
        api_key: $NPM_API_KEY
        on:
          branch: master
