language: node_js
node_js:
- '7'
before_install:
- npm install codecov -g
after_success:
- codecov -e TRAVIS_NODE_VERSION -f coverage/coverage.json
before_deploy:
- npm install uglify-es

deploy:
  provider: npm
  email: kariminfo0@gmail.com
  api_key:
    secure: DrqJoaX/2c/dvcB4qLCrpvpC2zfWUfvBSjf8Y+2fsSQ0hsSvLmtlet5bsvOL8UkEKS6sIhhp5mem6g04lLlNLIl80EEWDblYm8lvhUwOg1qrV/smVYz0ymKdilKpDkyf6lSSykgj5sGRUMmFHGNL2yBN73VhSmDHIamsY4IuuFsOwuHugw3q+P1oTrXd2O9cnlJNbIrlKQ6/au61hKZL7hHCylcEmq33blTWiKcBL05lmzApeCZDLRODwRiiOLQyeJAv+YjLcljIWOHbUjnLd44tEHMH4ByNIQwo7NoTxDJnhgt1mDcHDFUVcIojLp/W+LnQyF+xDE1v5UO3ouRUdMO9d+uAWknN1dU3VD+a3BLIH3n5mAFHEQ2NJKnqtCFzt9HOkc5cUXMODqNDLybA0E3vXCCMvcYeOBMDk3QaY3nju9VIjU3io8oA93JsiDIWE8+DXU1OZ5BmtQeeLhJTlLv8/wQgRiJWCSiqQVnQKbisYCOisBdnQm9GigTBPUue4ZLvVNvqXYF1cgFqimjcZXC9syH/tvlJV/3mETZFRlJAWE1bfVig5ojgvqqssm0D3G6NPu671DC/Pl4qe33mF4bQwUq/X4NhdTzPzYBWP6/txBQb8+VDkOJ92sdhAXTjUtJgwL2/+SjHcRsJ+YfRSybrYMyTb65B5jTlT+lPBiE=
